name: Python package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Open Web Client Directory
        working-directory: ak4728/to-the-moon
        run: ls -la

      - name: Open Web Client Directory
        run: python ./main.py
